api.v1.tm.success-message=Success
api.v1.tm.success-response-code=200
api.v1.tm.validate-error-code=400
api.v1.tm.web-client-pool-size=50

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require

quarkus.datasource.username=postgres.zyioeckamtlidfghmbej
quarkus.datasource.password=${DB_PASSWORD:default_password}

quarkus.oidc.auth-server-url=https://zyioeckamtlidfghmbej.supabase.co/auth/v1
quarkus.oidc.token.issuer=https://zyioeckamtlidfghmbej.supabase.co/auth/v1

quarkus.oidc.roles.role-claim-path=user_metadata/role
quarkus.rest-client.auth-client.url=${quarkus.oidc.auth-server-url}


quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.headers=Content-Type,Authorization,apikey,Accept
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.http.limits.max-body-size=50M